--CHAMADA DA FUNCAO:
-- PELA SELECT
--  SELECT NOME(PARAMETRO) FROM TABELA
-- EX: SELECT UPPER(NOME_A) FROM ALUNOS;
-- SELECT SYSDATE FROM DUAL;
--
--DENTRO DE OUTROS PROGRAMAS
--VALOR_DIA:: SYSDATE;

CREATE OR REPLACE FUNCTION NOME (PARAMETRO)

  RETURN TIPO( VARCHAR )
    AS
      --VARIAVEIS
    BEGIN
      <CODE>
    END;