
CREATE OR REPLACE FUNCTION fn_par_impar(p number)
RETURN varchar2

AS
BEGIN
  IF MOD(p,2) = 0
    THEN RETURN 'PAR';
  ELSE RETURN 'IMPAR';
  END IF;
END;
/

--EXECUTANDO A FUNCTION
SELECT FN_PAR_IMPAR(5) FROM dual;