

CREATE OR REPLACE TRIGGER TG_CUSTO
  BEFORE INSERT
  ON CUSTO
  REFERENCING NEW AS NEW
  FOR EACH ROW
    DECLARE TOTAL NUMBER
    BEGIN
      SELECT COUNT()
    END;
      
CREATE OR REPLACE TRIGGER TG_MORADOR
  BEFORE INSERT
  ON MORADOR
  REFERENCING NEW AS NEW
  FOR EACH ROW
    DECLARE TOTAL NUMBER
    BEGIN
      SELECT COUNT(COD_MORADOR) INTO TOTAL FROM MORADOR
      WHERE LOWER(NOME_MORADOR) = LOWER(:NEW.NOME_MORADOR);
      IF TOTAL > 0
        THEN RAISE_APLICATION_ERROR(-20000, 'JÁ EXISTE')
    END;  